eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

microservice:
  payments-service:
    endpoints:
      payOrder:
        uri: http://PAYMENTS-SERVICE/payments/orders/pay
  products-service:
    endpoints:
      retrieveProductEndpoint:
        uri: http://PRODUCTS-SERVICE/products/%s
